# Generated by Django 4.2.11 on 2024-05-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rserve',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
