# Generated by Django 4.2.11 on 2024-05-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0002_alter_rserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rserve',
            name='reserve_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
