# Generated by Django 4.2.11 on 2024-05-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0003_alter_customuser_user_id_alter_rserve_reserve_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reserve_data',
        ),
        migrations.AddField(
            model_name='rserve',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='Reserve.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
