# Generated by Django 5.0 on 2023-12-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0006_customuser_reserve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='reserve',
            new_name='reserve_data',
        ),
    ]
